### PR TITLE
Xcode 9 back compatibility and animation flag public

### PR DESCRIPTION
**Pull request by seriyvolk83**
Please see last commits 3f583ae and e7c0eaf

### CODE REVIEW

**Comment by sroik** [comment]
please merge this one :)

**Comment by sroik** [comment]
@AEugene

**Comment by AEugene** [comment]
@sroik 
I no longer have write access for the repository. Ask @YuryGrinenko @thehavre @rnkyr

**Comment by sroik** [comment]
@YuryGrinenko @thehavre @rnkyr 
Can we continue to support this project ?

**Comment by rnkyr** [comment]
hello everyone!

looks like the PR introduces some offset-related logic changes (KolodaView.swift l203)

also please do not change default values to your needs. Koloda is a public library that already have some users. such kind of changes could break their work

regarding default values - we've just merged a PR that opens these properties, so you could change it outside the KolodaView class.
regarding offset changing - please provide separate PR

I'll merge all code from this MR that introduces xcode compatibility shortly

**Comment by seriyvolk83** [comment]
@rnkyr is right. Just consider the mentioned commits to apply

>Please see last commits 3f583ae and e7c0eaf

**Comment by rnkyr** [comment]
closed via #405
thank you for your contribution!

**Pull request closed without merging**
