### PR TITLE
Add isLoop property for looping cards

### PR DESCRIPTION
**Pull request by brownsoo**
I am using Koloda in project. 
Thanks koloda.
I added looping property. 
I will be glad if this feature is added in koloda.
If Another solution exists, please let me know...

### CODE REVIEW

**Comment by durgeshtrivedi** [comment]
Hi, can you please show How to use this.
I try to add the changes in the files but it is crashing.

**Comment by brownsoo** [comment]
Hi, 
I made simple example [Koloda-looping](https://github.com/brownsoo/Koloda-looing)
I am using this in my project. I have been no errors.
But I do not test this in many case..😅

**Comment by brownsoo** [comment]
I fixed the error - viewForCardAt delegation is getting 0 index after once looping.
Try simple example [Koloda-looping](https://github.com/brownsoo/Koloda-looing)

**Comment by durgeshtrivedi** [comment]
Hi, Thanks for the reply and the fixed you did. 
I want to loop the card when user click up only not in other case . So I should able to do that is one use case I am working. By using your code and writing this code in delegate I can disable the looping and can enable it only for up swipe.

    func koloda(_ koloda: KolodaView, shouldSwipeCardAt index: Int, in direction: SwipeResultDirection) -> Bool {
        switch direction {
        case .up:
            kolodaView.isLoop = true
        default: kolodaView.isLoop = false
        }
        return true
    }

The issue is,  it is crashing. Suppose I have 100 cards and I should loop only when up swipe else it work normal. So I do 10 -20 left swipe or right swipe and then I do up swipe. It should loop but it is crashing lot of time . If you guide me I will try to fix your code.

**Comment by brownsoo** [comment]
Ah~ I got know your intend.  I think you use another solution.  In the delegate ‘didSwipeCardAt‘, I think you can remove card  using the method ‘removeCardInIndexRange’. Also we remove data at that removing index. I will test this case.

**Comment by durgeshtrivedi** [comment]
Hi, 

After your current fix the crash due to index is fix and app not crashing any more .But Still the loop is not proper when you combine it with  left or right swipe , when you just want to loop for up swipe only .

When you left, right swipe the card should get removed from datasource and you array and only loop when it is up swipe . I am trying to figure out what need to be done and let you know if I succeed. You can even try at your end.

**Comment by brownsoo** [comment]
@durgeshtrivedi I updated example [Koloda-looping](https://github.com/brownsoo/Koloda-looing) for your purpose. And I make new Koloda branch "_feature-looping+deletion_". But I have not succeed. 😂
Now I am busy, so I gonna try this challenge in next week.

**Comment by durgeshtrivedi** [comment]
Thanks Brownsoo for looking into this, I really appreciated the time you spend to fix the things for me. I even not yet succeed. I will let you know if I figure out any thing by next week.

**Comment by keyhan76** [comment]
Great branch
Thanks a lot

**Comment by gelemias** [comment]
Hi, is there anything stopping this branch to be merge? this feature is really useful and I don't see why this couldn't included

**Pull request merged**
