### PR TITLE
Fixed Bug

### PR DESCRIPTION
**Pull request by lixiang1994**
Hello, 
fixed the vulnerability that the card could not respond due to the simultaneous call to swipe(.xx) during the dragging of the card.

### CODE REVIEW

**Comment by lixiang1994** [comment]
Operation process:
1. Running example
2. Drag the card, don't let go
3. Click a button
4. Finally, all cards are not responding

**Comment by lixiang1994** [comment]
Thanks 😄

**Comment by lixiang1994** [comment]
Process of occurrence

```
public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
       if let touchView = touch.view, let _ = touchView as? UIControl {
            return false
       }
       panGestureRecognizer.isEnabled = delegate?.card(cardShouldDrag: self) ?? true
       return true
}
```
If 
```
panGestureRecognizer.isEnabled = false
```

Quick swipe, Crazy fast swipe.

Sometimes this method will be executed.
```
func panGestureRecognized(_ gestureRecognizer: UIPanGestureRecognizer)
```
Resulting in
```
dragBegin = true
```

**Comment by lixiang1994** [comment]
Thanks, Looking forward to the early merger  😄

**Comment by lixiang1994** [comment]
@rnkyr

**Comment by lixiang1994** [comment]
@rnkyr  ??

**Comment by brownsoo** [comment]
Good fixing~ !! 
I hope to some code line breaks be removed.

**Comment by lixiang1994** [comment]
@brownsoo  👌

**Comment by lixiang1994** [comment]
https://github.com/Yalantis/Koloda/issues/416

**Comment by lixiang1994** [comment]
@AEugene @serejahh

**Comment by serejahh** [comment]
You should ask @rnkyr

**Comment by rnkyr** [comment]
hello everyone! sorry for being silent for too long

I'm about to release a new version that includes this PR. 
A big thank you for the fix! Looks good

**Comment by lixiang1994** [comment]
Thank you!

**Pull request merged**
