### PR TITLE
Fixed misalignment of background cards

### LINKED ISSUE #57: Background cards are misplaced
In some situations the background cards don't follow a vanishing line. This can be caused by non-rectangular cards or off-centered placement of the koloda view (IIRC). Anyway, the easiest step to reproduce is to set the `backgroundCardsScalePercent` to `0.9`. 

# Expected
screen shot 2015-10-26 at 15 27 43

# Actual
screen shot 2015-10-26 at 15 25 37

### PR DESCRIPTION
**Pull request by sebastianludwig**
by calculating background card left margin dynamically. Closes #57. Any feedback appreciated.

### CODE REVIEW

**Comment by AEugene** [comment]
Hi @sebastianludwig 
Thank you for contribution. But I actually don't like current implementation. I see ```layoutDeck``` method as universal layout trigger, but your current implementation depends on the particular layout, so this solution won't work if you want to layout background cards as mosaic of tiles for example.

**Comment by sebastianludwig** [comment]
Thanks for the open discussion :disappointed: 

How exactly would your current implementation support a mosaic layout of background cards? `backgroundCardsLeftMargin` is hard coded to 8.

**Comment by AEugene** [comment]
I'm just pointing that this type of issues should be handled within ```frameForCardAtIndex(index: UInt)``` method. Take a look at #67

**Comment by sebastianludwig** [comment]
OIC, yes, that solution is a lot cleaner.

**Pull request closed without merging**
