### PR TITLE
Public animation constants

### PR DESCRIPTION
**Pull request by noordawod**
Instead of writing a custom class altogether that overrides default behaviour, this is a middle-ground way of thinking. Provide the default and allow the user to override if necessary. Backward-compatible.

### CODE REVIEW

**Comment by Tykhonkov** [comment]
Hello @noordawod , thank you for pull request. There is issue in your PR, this variables shouldn't been static var, because it affects on behavior of all ```DraggableCardView``` instances it can be shitty if you have several ```KolodaView``` instances and want different animations for each.
Better approach will be to pass required values through ```DraggableCardDelegate``` and ```KolodaViewDelegate``` from your controller.

**Comment by noordawod** [comment]
Fair point, @Tykhonkov. Meanwhile, I pushed a new commit which addresses your reservations.

Is it good for you now?

**Comment by noordawod** [comment]
A pleasure :)

**Comment by noordawod** [comment]
@Tykhonkov 

I think you or someone else changed my suggested pull (this one) and removed "self." from few places. This has caused a compilation error.

This is now addressed in #312.

**Pull request merged**
