### PR TITLE
Fixed card distortion by applying pan gesture transforms in order.

### LINKED ISSUE #59: Dragged cards are distorted
And the "fly off the finger" when dragged. This is due to the transform operation order in [`DraggableCardView panGestureRecognized`](https://github.com/Yalantis/Koloda/blob/908106b9b243274fc2e5d7133196a4de99faec6f/Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift#L215). Transforms are combined in order, so rotating first and scaling second scales the rotation. Also setting the center seems to mess with the transforms. This might relate to #54.

### PR DESCRIPTION
**Pull request by sebastianludwig**
This closes #59 and maybe #54 as well. @lunswor could you check that out?

### CODE REVIEW

**Comment by lunswor** [comment]
Wow, thanks, it solves this for me!

**Comment by orkenstein** [comment]
Pls, merge this asap! @shytyk

**Comment by orkenstein** [comment]
@sebastianludwig 
Hm, as a drawback this update brings some animation issues:
1) There is a delay between and of pan and "disappear to left/right" animation. It's on iPhone 4s. I think because of some heavy task in main thread.
2) When this animation starts, view gets immediately resized to original size. 
For example, i'm slowly dragging upper page closely to the edge, page becomes, say, 80% scale, and when I end dragging, it immediately scales back to 100%.

**Comment by sebastianludwig** [comment]
Mmmmhh..allright, thanks for the feedback - I'll look into it tomorrow.

**Comment by orkenstein** [comment]
Cool. After all, it's already much better.

**Comment by sebastianludwig** [comment]
Now this got slightly out of hand. I was _not_ able to reproduce your issues, but noticed a glitch when letting go of the cards. The fix was to animate the layer instead of the view transform which seems like a cleaner approach to me anyway. The result is even better because the card completely sticks to the finger now.

I also tested the example on my iPhone 4S, however on iOS 7 and did not notice any lag between letting go and and the start of the animation. Also there shouldn't be an expensive operation..at least I didn't see one. Could you take a video? (QuickTime can capture your device screen when it's connected).

**Comment by AladinWay** [comment]
@sebastianludwig thank you for the effort and for sharing. Actually I confirm that there a glitch that happens randomly when we start dragging a card slowly in the iPhone 4s. Basically there is about 2px of the card that stay printed in the background and when you pass the card over that friezed area it's gone

**Comment by AladinWay** [comment]
Please take a look at my issue #64 for a video shot

**Comment by sebastianludwig** [comment]
@AladinWay does this only happen on the 4S or on other devices as well? Which iOS version are you using?

**Comment by AladinWay** [comment]
@sebastianludwig actually I have just tested on iPhone 4s iOS 9.0.2 here is the project : 
http://www88.zippyshare.com/v/kPj7eBlb/file.html

**Comment by sebastianludwig** [comment]
@AladinWay, thanks for the example project. While I was still unable to reproduce the issue because I don't have an iPhone 4S with iOS 9 at hand (I might next week), could you check if the issue persists with this PR?

**Comment by sebastianludwig** [comment]
@orkenstein, could you please re-check if your issues are resolved with my latest changes?

**Comment by orkenstein** [comment]
@sebastianludwig which commit should I pick? `f916631`?

**Comment by sebastianludwig** [comment]
Yes, that'd be great.

**Comment by sebastianludwig** [comment]
Just for reference: AladinWay's issue #64 has _not_ been introduced by this PR.

**Comment by orkenstein** [comment]
@sebastianludwig sorry for a delay!
It looks like Quick Time can not capture video via old 20pin cable. But I've recorded video with simulator. It behave much the same way.

1) It's hard to reproduce dragging issue on simulator, but take a look:
https://yadi.sk/d/J_N3THwukDoBY
The problem as it appears on device: when you swipe card left/right it waits for a while to go off screen. This effect disappear when only 2 cards left on the screen. I think there is heavy animation somewhere and it blocks main thread.

2) Card resizing almost gone. There is alight resize when you end gesture, but looks ok.

And I've found one more glitch. It may be related or may be not:
https://yadi.sk/d/nD1kUo_YkDpcQ
It's may be the same issue as @AladinWay  stated before.

**Comment by sebastianludwig** [comment]
I do have an iPhone 4S, iOS 9.1 now.

@AladinWay: I was able to reproduce the glitch very reliable with the current master, but not with f916631. Could you provide an example project using that version that still shows the glitch?

@orkenstein: Thanks for your feedback! Your second issue is definitely one and a new one - I'll look into it.

However I'm having a hard time to see exactly what you're demonstrating in your first video. At what time in the video is the delay apparent? And where is gone? And what time span are we talking about when you say "for a while"? Like 0.5s or 0.1s? What do I have to look for? (I already watched the video at x0.25 speed..)

**Comment by AladinWay** [comment]
@sebastianludwig  I have tested it it happens in iPhone 4s iOS 9.0.2 I guess it's a performance, animation or pan gesture issue... thanks for help here is the result of your mentioned commit : https://github.com/sebastianludwig/Koloda/archive/fix_distortion.zip 

https://youtu.be/mD2e_HOtddI

**Comment by sebastianludwig** [comment]
@orkenstein, I implemented the letting go animation as layer animation (like the dragging animation itself). The mix of layer animation with view animation caused the card to jump back just a few pixels when letting go. This could have looked like a delay. Please check if your issue is resolved.

Apart from that I can't think of any heavy duty task or animation, let alone on the main thread with the potential to cause a delay. If you could provide a pointer to a specific animation which causes the delay for your (by debugging and disabling them one by one), I'd be happy to investigate further.

@AEugene, @maximletushov: any opinions or feedback?

**Comment by AEugene** [comment]
Hi, @sebastianludwig . Thank you for PR. Overall solution is great. I wanted to remove UIView animation, but didn't have time for this. However I think that 2 dependencies is too much for this lib. So now I'm trying to build new solution with pop framework based on your PR and corrections.

**Comment by sebastianludwig** [comment]
I would have liked to use pop but it doesn't support transform animations. See facebook/pop#14. I didn't really look into it, but is POP a necessary dependency?

**Comment by AEugene** [comment]
@sebastianludwig POP is not necessary. All pop layer animations are based on transforms(because it's based on CABasicAnimation), you just can't directly set the transform, so there is no need to add JNWSpringAnimation. I've already reproduced all your animations with POP Layer animation. I'll come up with result PR till the end of this week. Anyway I really appreciate your help.

**Comment by sebastianludwig** [comment]
Great! Looking forward to see your solution. I haven't worked with POP yet.

**Comment by AEugene** [comment]
hi @sebastianludwig . Take a look at #71

**Pull request closed without merging**
