### PR TITLE
update func names for 3.1.1

### PR DESCRIPTION
**Pull request by muhasturk**
BTW Readme file needs update method names for recent koloda version.

### CODE REVIEW

**Comment by AEugene** [comment]
hi @muhasturk . Could you fix conflicts?

**Comment by muhasturk** [comment]
I didnt get it where the conflicts are?

**Comment by AEugene** [comment]
Merge latest master in your branch.

**Comment by serejahh** [comment]
Updated manually, so the PR is closed. Thanks for the contribution @muhasturk

**Pull request closed without merging**
