### PR TITLE
Expose method for overriding card `actionMargin`

### PR DESCRIPTION
**Pull request by aemengo**
Some of our end users have been commenting on how taxing it is to swipe cards. Allowing the ability to override the swipe distance might prove useful for some.

### CODE REVIEW

**Comment by AEugene** [comment]
hi @aemengo . Please update your PR to latest delegate syntax.

**Comment by aemengo** [comment]
PR updated.

**Comment by AEugene** [comment]
@aemengo There is merge conflict, please update your branch with latest develop.

**Comment by aemengo** [comment]
Updated.

**Comment by AEugene** [comment]
@aemengo Thanks for contribution. We'll update pod version in few days.

**Pull request merged**
