### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AndreiVidrasco**

### CODE REVIEW

**Comment by freaqed** [comment]
Hey @AndreiVidrasco!
Your PR doesn't make any sense, so I'm going to decline it as not appropriate.

**Comment by AndreiVidrasco** [comment]
Hi @freaqed 

Because there is no empty line between last definition and Methods, README currently is rendered like
screen shot 2017-05-11 at 13 44 46

With one empty line, text "The count of displayed cards in the KolodaView." will be rendered with proper text style(as documentation) and Methods as header
screen shot 2017-05-11 at 13 45 22

Please, check these screenshot

**Comment by freaqed** [comment]
Oh, I see now. Will schedule that PR to a next update.
Sorry for that and thanks for contribution!

**Comment by AndreiVidrasco** [comment]
Probably should have wrote this, when I opened PR.
Thanks for re-opening :)

**Pull request merged**
