### PR TITLE
Fixed crash when view appears but no dataSource has been set yet.

### PR DESCRIPTION
**Pull request by NitWitStudios**

### CODE REVIEW

**Comment by NitWitStudios** [comment]
Example - When data is still being loaded before attempting to call the KolodaView:

    override func viewDidLoad() {
        super.viewDidLoad()

        if items.count == 0 {
            ...load data...
            ...then set dataSource and delegate...
        } else {
            kolodaView.dataSource = self
            kolodaView.delegate = self 
        }
    }

**Comment by NitWitStudios** [comment]
Bump.

**Comment by AEugene** [comment]
hi @NitWitStudios . I think It's not the fix you're looking for. KolodaView designed this way, because it's data-source driven view, so the dataSource property is mandatory. I strongly not recommend using this approach with data-source driven views. I think you should setup empty dataSource, before Koloda needs it, and then update items in network request callback. @maximletushov, what do you think?

**Comment by maximletushov** [comment]
I think that main cause of misunderstanding here that datasource is declared like implicitly unwrapped optional but it can be not set by users.
```
public weak var dataSource: KolodaViewDataSource!
```
I would declare it like a common optional
```
public weak var dataSource: KolodaViewDataSource?
```

**Comment by AEugene** [comment]
I agree. It's fixed with #74 .

**Pull request closed without merging**
