### PR TITLE
Swift 3 update 

### PR DESCRIPTION
**Pull request by dimakomar**
Updated both library and example to swift 3.0 @AEugene @alarin

### CODE REVIEW

**Comment by alarin** [comment]
Carthage needs xcode project to build.

**Comment by serejahh** [comment]
@dimakomar Thanks for the PR! We want to create more Swifty API, not just convert syntax from Swift 2 to Swift 3. That's the reason why we still have `swift-3` branch. Any changes should be merged to the branch. When it's ready, we'll merge it to `master`

**Comment by samad5353** [comment]
How can i get the updated version for swift3

**Comment by serejahh** [comment]
@samad5353 Add to your podspec:
```
pod 'Koloda', :git => 'https://github.com/Yalantis/Koloda.git …', :branch => 'swift-3'
```

**Comment by plflanagan** [comment]
Using the swift-3 branch is resulting in many various build issues currently. Is it actually Swift 3/clean?

**Comment by serejahh** [comment]
@plflanagan when it's ready, we will merge it to `master`. Now it's still in development

**Pull request closed without merging**
