### PR TITLE
Fixed glimpsy animation on fast swiping

### PR DESCRIPTION
**Pull request by AEugene**
Fixed glimpsy animation on fast swiping

### CODE REVIEW

**Comment by jasan-s** [comment]
Will cocoapod reflect this commit? so if i run pod install again?

**Comment by AEugene** [comment]
After merge, sure.

**Comment by jasan-s** [comment]
Newbie question again. Will you merge the repo?

**Comment by AEugene** [comment]
Reviewer will merge the repo)

**Comment by robertherdzik** [comment]
Great job, this commit will fix #24 issue.

**Comment by jasan-s** [comment]
cocoapods still showing version "1.1.1", so just made manual changes, It fixed the error

**Pull request merged**
