### PR TITLE
Update to Swift 5.0

### PR DESCRIPTION
**Pull request by maxxfrazer**
- Updated LatestSwiftMigration to 5.0
  - Only code change was index(of:) -> firstIndex(of:)
- Changed developmentRegion code to ISO 639-1 (preferred)
- Automatic change from `${SRCROOT}/Pods` to `${PODS_ROOT}`
--------
- Enhancement
- Low Priority

### CODE REVIEW

**Comment by maxxfrazer** [comment]
@rnkyr just making sure you get pinged about this PR 👍

**Comment by rnkyr** [comment]
hi @maxxfrazer!

thank you for your contribution 👍👍👍

yep, I've notifications set up. but currently can't take this into consideration
I'll try to find someone from our team to take a look shortly

**Comment by maxxfrazer** [comment]
Cheers @rnkyr! I've noted that it's low priority in the description, so whenever you or your team can take a look that'd be grand.

**Comment by cbess** [comment]
any timeline on this being merged?

**Pull request merged**
