### PR TITLE
Pan issue

### PR DESCRIPTION
**Pull request by AEugene**
Fixed pan animation issue. Refactored data source and delegate methods naming. Minor refactoring.

### CODE REVIEW

**Comment by AEugene** [comment]
Fixed #54 , #59 , #63 , #64

**Comment by maximletushov** [comment]
Looks good ! Thanks!  :shipit:

**Comment by sebastianludwig** [comment]
Nice work! However this implementation does not set the anchor point of the layer which causes the card to move away under your finger. For example, if you hold a card on the upper right corner and drag it to the left side, it slides away and by the time the upper right corder has reached the left side of the screen, your finger isn't even on the card anymore. 

#60 in contrast sets the layer anchor point to the point where the user touched the card first which in turn causes the card to rotate and scale around that point. As a result the card sticks to the finger as expected when moving.

**Comment by AEugene** [comment]
Thanks @sebastianludwig . I'll take a look at it, I've also noticed some issues with fast swiping. So I'll merge this later, when I fix the issue

**Comment by paperkettle** [comment]
Also noticed the "your finger isn't even on the card anymore" / anchoring issue. Makes the dragfeel a bit indirect. Was considering adding an option to disable resizing as well — any interest?

**Comment by AEugene** [comment]
hi @sebastianludwig. Could you test latest commit on this branch? I've updated animation using your anchor point issue

**Comment by AEugene** [comment]
Fixes #75

**Comment by sebastianludwig** [comment]
The dragging animation looks fine now. However when dragging a card by its upper right corner towards the left edge and letting go, the card moves a bit and then disappears while still being on screen.

Also the last card disappears without animation. But that issues hasn't been introduced by this PR, it's been like this before.

**Comment by AEugene** [comment]
@sebastianludwig Issue with last card caused by example, resettingCard number forces Koloda to clear subviews and load from the beginning, it shouldn't be in real projects. I'll take a look at finish state of animation again.

**Comment by sebastianludwig** [comment]
Looks like the card isn't moving far enough to the left with the anchor point being set to the far right edge of the card.

**Comment by lunswor** [comment]
Hi @AEugene, one small think i've noticed is the spelling of kolodaDidRuntOutOfCards. Another thing i've noticed is the first card occasionally appears to be cropped to around 20% of the size, not sure if its just my implementation but only seen this with this pull request.

**Comment by AEugene** [comment]
hi @lunswor . Thanks for noticing. I haven't reproduced your issue in Example. Could you provide some steps?

**Comment by lunswor** [comment]
I'll try an create a sample branch later today. The thing is i've only seen it a few times so could be very tricky to reproduce.

**Comment by Bashta** [comment]
@AEugene @lunswor i have the same problem occasionally. Resolved it by returning false to this methods `kolodaShouldApplyAppearAnimation` `kolodaShouldTransparentizeNextCard` `kolodaShouldMoveBackgroundCard`

**Comment by AEugene** [comment]
@Bashta Actually, this method was made mainly for Example project. Is appear animation really useful?

**Comment by lunswor** [comment]
@AEugene I use the appear animation.

**Comment by Bashta** [comment]
@AEugene I dont really need it in my current project but its nice to have for other users that actually prefers the appear animation.

**Comment by AEugene** [comment]
@lunswor @Bashta I still can't reproduce it

**Comment by lunswor** [comment]
I've not been able to reproduce today, soon as it happens again i'll take a screen shot incase that helps. I'm not sure how to even debug this when it happens rarely.

**Comment by Bashta** [comment]
@AEugene ill give it a go tomorrow as soon as i have a minute!

**Comment by AEugene** [comment]
@lunswor @Bashta hi there. I've refactored appearance as layer animation. Could you try to reproduce issue again?

**Comment by lunswor** [comment]
Sure thanks. Ill let you know.

**Comment by Bashta** [comment]
@AEugene Just gave it a try and everything looks fine. Will let you know if i have any issues in the future.

**Comment by AEugene** [comment]
@sebastianludwig @paperkettle @lunswor @Bashta @maximletushov Thanks again for contribution

**Pull request merged**
